server:
  port: 8085
spring:
  application:
    name: "account"

  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

  datasource:
    url: jdbc:mysql://localhost:3310/accountDb
    username: root
    password: root
  profiles:
    active: "prod"

  config:
    import: "optional:configserver:http://localhost:8071/"

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

logging:
  level:
    com:
      eazyBank:
        Account: DEBUG

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 5
      waitDurationInOpenState: 10s
      failureRateThreshold: 50


resilience4j.retry:
  configs:
    default:
      maxAttempts: 3
      waitDuration: 1000ms
      enable-exponential-backoff: true
      exponential-backoff-multiplier: 2
      retryExceptions:
        - feign.FeignException
        - java.net.ConnectException
        - java.io.IOException
  instances:
    cardServiceRetry:
      baseConfig: default
