server:
  port: 8082

spring:
  application:
    name: "card"

  datasource:
    url: jdbc:mysql://localhost:3311/cardDb
    username: root
    password: root
  profiles:
    active: "qa"

  config:
    import: "optional:configserver:http://localhost:8071/"
