server:
  port: 8081

spring:
  application:
    name: apigateway

  config:
    import: "optional:configserver:http://localhost:8071/"

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      access: unrestricted


resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 5
      waitDurationInOpenState: 10s
      failureRateThreshold: 50


logging:
  level:
    org.springframework.cloud.gateway.filter.factory.RetryGatewayFilterFactory: DEBUG